@url = http://localhost:5008
@id = 8007ef3f-d593-4f69-900e-414dfe92db40

###
GET {{url}}/products

###
GET {{url}}/reports/products/{{id}}

###
POST {{url}}/reports/products
Content-Type: application/json

{
    "maxRank": 5
}
